# Generated by Django 2.2.9 on 2019-12-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('youtube_URL', models.URLField(null=True)),
                ('embedded', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('focus', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig')], default=1)),
                ('tags', models.ManyToManyField(to='videos.VideoTag')),
            ],
        ),
    ]
