# Generated by Django 2.0.8 on 2019-09-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=150, null=True)),
                ('youtube_URL', models.URLField(null=True)),
                ('embedded', models.URLField(blank=True, null=True)),
                ('beskrivelse', models.TextField(blank=True, null=True)),
                ('fokuspunkt', models.TextField(blank=True, null=True)),
                ('vanskelighetsgrad', models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['navn'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='videos.VideoTag'),
        ),
    ]
