# Generated by Django 2.2.9 on 2020-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTag',
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='songs.Tag'),
        ),
    ]
