# Generated by Django 2.0.8 on 2019-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_delete_artist'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='beskrivelse',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fokuspunkt',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='navn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='songs.Tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='vanskelighetsgrad',
            field=models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig'), (3, 'Avansert')], default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
