# Generated by Django 2.2.5 on 2019-12-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotag',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='beskrivelse',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fokuspunkt',
        ),
        migrations.RemoveField(
            model_name='video',
            name='navn',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vanskelighetsgrad',
        ),
        migrations.RemoveField(
            model_name='videotag',
            name='navn',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig')], default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='videotag',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
