# Generated by Django 2.0.8 on 2019-08-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='video',
            name='beskrivelse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='fokuspunkt',
            field=models.TextField(null=True),
        ),
    ]
