# Generated by Django 2.0.8 on 2019-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190220_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embedded',
            field=models.URLField(blank=True, null=True),
        ),
    ]
