# Generated by Django 2.0.8 on 2019-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190810_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='beskrivelse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='fokuspunkt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
