# Generated by Django 2.0.8 on 2019-08-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190816_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotag',
            options={'ordering': ['navn']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='youtube',
            new_name='youtube_URL',
        ),
        migrations.RenameField(
            model_name='videotag',
            old_name='name',
            new_name='navn',
        ),
        migrations.AlterField(
            model_name='video',
            name='vanskelighetsgrad',
            field=models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig')], default=1),
        ),
    ]
