# Generated by Django 2.2.9 on 2020-01-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200102_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='video',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Lett'), (2, 'Middels'), (3, 'Vanskelig')], default=1, verbose_name='Vanskelighetsgrad'),
        ),
        migrations.AlterField(
            model_name='video',
            name='focus',
            field=models.TextField(blank=True, null=True, verbose_name='Fokuspunkt'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Tittel'),
        ),
    ]
