# Generated by Django 2.2.9 on 2020-01-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200104_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videoer'},
        ),
    ]
