# Generated by Django 2.2.9 on 2020-01-26 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='earlybird',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='joined',
        ),
        migrations.AddField(
            model_name='participant',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dato påmeldt'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_earlybird',
            field=models.BooleanField(default=False, verbose_name='Earlybird'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Har betalt'),
        ),
    ]
