# Generated by Django 2.2.9 on 2020-01-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200126_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='earlybird_price',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
