# Generated by Django 2.2.9 on 2020-01-21 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200120_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start', 'title'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_eventset', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_eventset', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av'),
        ),
    ]
