# Generated by Django 2.2.9 on 2020-01-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200127_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='earlybird_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='earlybirds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
