# Generated by Django 2.2.9 on 2020-01-03 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(max_length=100, unique=True)),
                ('last_edited', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_pageset', to=settings.AUTH_USER_MODEL)),
                ('last_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_pageset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
