# Generated by Django 2.2.9 on 2020-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(help_text='URL som bruker i adressefelt', max_length=100, unique=True),
        ),
    ]
