# Generated by Django 2.2.9 on 2020-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='private',
            field=models.BooleanField(blank=True, default=True, verbose_name='Privat mappe'),
        ),
    ]
