# Generated by Django 2.2.9 on 2020-01-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folderset', to='auth.Permission', verbose_name='Rettigheter'),
        ),
    ]
