# Generated by Django 2.2.9 on 2020-01-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_folder_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folderset', to='auth.Permission', verbose_name='Rettighet'),
        ),
    ]
