# Generated by Django 2.2.9 on 2020-01-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20200103_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
