# Generated by Django 2.2.9 on 2020-01-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20200103_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='private',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
