# Generated by Django 2.2.9 on 2020-01-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20200104_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Mappe', 'verbose_name_plural': 'Mapper'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Side', 'verbose_name_plural': 'Sider'},
        ),
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_folderset', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='last_edited',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sist redigert'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='last_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_folderset', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Innhold'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_pageset', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='page',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='wiki.Folder', verbose_name='Mappe'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_edited',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sist redigert'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_pageset', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av'),
        ),
        migrations.AlterField(
            model_name='page',
            name='private',
            field=models.BooleanField(blank=True, default=True, verbose_name='Privat side'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Tittel'),
        ),
    ]
