# Generated by Django 2.2.9 on 2020-01-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='event_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_event', to='accounts.Theme', verbose_name='Event-tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background',
            field=models.CharField(blank=True, default=None, help_text='Bildeaddresse', max_length=1000, null=True, verbose_name='Bakgrunn URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='color',
            field=models.CharField(blank=True, default=None, help_text='css syntax', max_length=1000, null=True, verbose_name='Tekstfarge'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer',
            field=models.CharField(blank=True, default=None, help_text='css syntax', max_length=1000, null=True, verbose_name='Footer farge'),
        ),
    ]
