# Generated by Django 2.2.9 on 2020-01-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='background',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
