# Generated by Django 2.2.5 on 2019-10-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_spotifytoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='string',
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
