# Generated by Django 2.2.9 on 2020-01-02 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200102_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '------'), (1, 'lead'), (2, 'follow'), (3, 'hjelpeinstruktør'), (3, 'annet')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
