# Generated by Django 2.2.9 on 2020-01-25 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200125_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_footer', to='accounts.Theme', verbose_name='Footer-tema'),
        ),
        migrations.AddField(
            model_name='settings',
            name='input_group_bg',
            field=models.CharField(blank=True, default=None, help_text='css syntax', max_length=1000, null=True, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AddField(
            model_name='settings',
            name='input_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_input', to='accounts.Theme', verbose_name='Input-tema'),
        ),
        migrations.AddField(
            model_name='settings',
            name='link_color',
            field=models.CharField(blank=True, default=None, help_text='css syntax', max_length=1000, null=True, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AddField(
            model_name='settings',
            name='main_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_main', to='accounts.Theme', verbose_name='Hoved-tema'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, help_text='CSS eg: blue, rgba(0,0,255, 0.5)', max_length=1000, null=True, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_color',
            field=models.CharField(help_text='CSS eg: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Linkfarge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_hover_color',
            field=models.CharField(help_text='CSS eg: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Link hover farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_color',
            field=models.CharField(help_text='CSS eg: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Tekstfarge'),
        ),
    ]
