# Generated by Django 2.0.8 on 2019-08-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_spotify_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='superuser',
            new_name='is_superuser',
        ),
    ]
