# Generated by Django 2.2.9 on 2020-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='type',
            field=models.IntegerField(choices=[(0, '------'), (1, 'lead'), (2, 'follow'), (3, 'hjelpeinstruktør'), (4, 'annet')], default=0),
        ),
    ]
