# Generated by Django 2.0.8 on 2019-08-20 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190820_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('background_color', models.CharField(max_length=140)),
                ('link_color', models.CharField(max_length=140)),
                ('link_hover_color', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='course_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_course', to='accounts.Theme'),
        ),
        migrations.AddField(
            model_name='settings',
            name='song_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_song', to='accounts.Theme'),
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settings',
            name='video_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_video', to='accounts.Theme'),
        ),
    ]
