# Generated by Django 2.2.9 on 2020-01-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200125_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='navbar',
        ),
        migrations.AddField(
            model_name='settings',
            name='color',
            field=models.CharField(blank=True, default=None, help_text='color', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='background',
            field=models.CharField(blank=True, default=None, help_text='background-image-url', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer',
            field=models.CharField(blank=True, default=None, help_text='background-color', max_length=1000, null=True),
        ),
    ]
