# Generated by Django 2.2.9 on 2020-01-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200125_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='color',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='input_group_bg',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='link_color',
        ),
    ]
