# Generated by Django 2.2.9 on 2020-01-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200125_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='scrollbar',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Scrollbar farge'),
        ),
    ]
