# Generated by Django 2.0.8 on 2019-08-20 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190820_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='course_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_course', to='accounts.Theme'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='song_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_song', to='accounts.Theme'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='video_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_video', to='accounts.Theme'),
        ),
    ]
