# Generated by Django 2.2.9 on 2020-01-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200103_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['type'], 'verbose_name': 'Instruktør', 'verbose_name_plural': 'Instruktører'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Instilling', 'verbose_name_plural': 'Instillinger'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['user', 'name'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temaer'},
        ),
        migrations.RemoveField(
            model_name='theme',
            name='creator',
        ),
        migrations.AlterField(
            model_name='settings',
            name='account_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_account', to='accounts.Theme', verbose_name='Bruker tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='course_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_course', to='accounts.Theme', verbose_name='Kurs tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='song_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_song', to='accounts.Theme', verbose_name='Musikk tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Tilhører'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='video_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_video', to='accounts.Theme', verbose_name='Turbibliotek tema'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(max_length=140, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_color',
            field=models.CharField(max_length=140, verbose_name='Link farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_hover_color',
            field=models.CharField(max_length=140, verbose_name='Link hover farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(blank='False', max_length=140, null=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Fornavn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Etternavn'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Mobilnummer'),
        ),
    ]
