# Generated by Django 2.2.9 on 2020-01-04 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200104_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='text_color',
            field=models.CharField(help_text='CSS: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Tekst farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(help_text='CSS: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_color',
            field=models.CharField(help_text='CSS: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Link farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='link_hover_color',
            field=models.CharField(help_text='CSS: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Link hover farge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Dersom eier er satt, vil temaet være privat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Eier'),
        ),
    ]
