# Generated by Django 2.2.9 on 2020-01-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200104_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='wiki_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings_as_wiki', to='accounts.Theme', verbose_name='Wiki tema'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, help_text='CSS: blue, rgba(0,0,255, 0.5)', max_length=140, null=True, verbose_name='Bakgrunnsfarge'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=140, null=True, verbose_name='Navn'),
        ),
    ]
