# Generated by Django 2.2.9 on 2020-01-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200104_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='account_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_account', to='accounts.Theme', verbose_name='Bruker tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='course_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_course', to='accounts.Theme', verbose_name='Kurs tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='song_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_song', to='accounts.Theme', verbose_name='Musikk tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='video_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_video', to='accounts.Theme', verbose_name='Turbibliotek tema'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='wiki_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_as_wiki', to='accounts.Theme', verbose_name='Wiki tema'),
        ),
    ]
