# Generated by Django 2.2.5 on 2019-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='mediaroot/')),
            ],
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('bpm', models.SmallIntegerField(blank=True, null=True)),
                ('spotify_URL', models.URLField()),
                ('spotify_URI', models.CharField(blank=True, max_length=300, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='songs.SongTag')),
            ],
        ),
    ]
