# Generated by Django 2.0.2 on 2018-10-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='songs.Tag'),
        ),
    ]
