# Generated by Django 2.0.8 on 2019-08-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='URI',
            new_name='spotify_URI',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spotify',
            new_name='spotify_URL',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='tittel',
        ),
        migrations.RenameField(
            model_name='songtag',
            old_name='name',
            new_name='navn',
        ),
    ]
