# Generated by Django 2.2.9 on 2020-01-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongTag',
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, to='songs.Tag'),
        ),
    ]
