# Generated by Django 2.2.9 on 2019-12-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20191227_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('context', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
