# Generated by Django 2.0.2 on 2018-10-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20181014_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='URI',
            field=models.URLField(blank=True, null=True),
        ),
    ]
