# Generated by Django 2.2.9 on 2020-01-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200101_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
