# Generated by Django 2.2.9 on 2020-01-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200102_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['bpm', 'title'], 'verbose_name': 'Sang', 'verbose_name_plural': 'Sanger'},
        ),
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.SmallIntegerField(blank=True, help_text='Helst antall partall per minutt', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_URI',
            field=models.CharField(help_text='Høyre klikk på sang -> Share -> Copy Spotify URI', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_URL',
            field=models.URLField(help_text='Høyre klikk på sang -> Share -> Copy Song Link', null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='context',
            field=models.CharField(blank=True, help_text='Mellomrom-separerte nøkkelord for å relatere tag til kategori (Blank for ikke spesifikk type). Bruk: song, course eller video.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Tittel'),
        ),
    ]
