# Generated by Django 2.0.8 on 2018-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20181023_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='URI',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify',
            field=models.URLField(),
        ),
    ]
