# Generated by Django 2.0.8 on 2019-02-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20181025_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
