# Generated by Django 2.0.8 on 2019-02-09 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0005_auto_20181025_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('target_group', models.TextField()),
                ('external', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('int_duration', models.DurationField(default=90)),
                ('female_instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='female_instructor', to=settings.AUTH_USER_MODEL)),
                ('male_instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='male_instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.TimeField()),
                ('duration', models.DurationField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='songs.Song')),
            ],
        ),
    ]
