# Generated by Django 2.0.8 on 2019-02-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='nr',
            field=models.IntegerField(default=None),
        ),
    ]
