# Generated by Django 2.2.9 on 2020-01-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
