# Generated by Django 2.2.5 on 2019-12-27 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20190924_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dato',
        ),
        migrations.RemoveField(
            model_name='course',
            name='følger',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fører',
        ),
        migrations.RemoveField(
            model_name='course',
            name='kommentarer',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slutt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sted',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tittel',
        ),
        migrations.RemoveField(
            model_name='section',
            name='beskrivelse',
        ),
        migrations.RemoveField(
            model_name='section',
            name='tittel',
        ),
        migrations.RemoveField(
            model_name='section',
            name='varighet',
        ),
        migrations.AddField(
            model_name='course',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='female_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='male_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='', max_length=140, null=True),
        ),
    ]
