# Generated by Django 2.2.9 on 2020-01-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200113_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Eksternkurs'),
        ),
    ]
