# Generated by Django 2.0.8 on 2019-08-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190818_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='hvor',
            new_name='sted',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='sang',
            new_name='song',
        ),
        migrations.AddField(
            model_name='section',
            name='kommentarer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='beskrivelse',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
