# Generated by Django 2.2.9 on 2019-12-31 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20191227_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
