# Generated by Django 2.2.9 on 2020-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200101_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
