# Generated by Django 2.0.8 on 2019-02-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190209_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='nr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
