# Generated by Django 2.0.8 on 2019-08-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190818_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='kurs',
            new_name='course',
        ),
    ]
