# Generated by Django 2.0.8 on 2019-02-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190209_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='nr',
        ),
    ]
