# Generated by Django 2.0.8 on 2019-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_section_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
