# Generated by Django 2.0.8 on 2019-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190818_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='varighet',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
