# Generated by Django 2.0.8 on 2019-08-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_embedded'),
        ('courses', '0008_auto_20190803_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video',
            field=models.ManyToManyField(to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
