# Generated by Django 2.0.8 on 2019-08-18 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190818_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='varighet',
        ),
        migrations.RemoveField(
            model_name='section',
            name='kommentarer',
        ),
        migrations.AddField(
            model_name='course',
            name='kommentarer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='varighet',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
