# Generated by Django 2.2.9 on 2020-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200102_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bulk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
