# Generated by Django 2.0.8 on 2019-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190818_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='varighet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
