# Generated by Django 2.0.8 on 2019-08-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_embedded'),
        ('courses', '0009_auto_20190803_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songs.Song'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='video',
        ),
        migrations.AddField(
            model_name='section',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video'),
        ),
    ]
