# Generated by Django 2.2.9 on 2020-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
