# Generated by Django 2.0.8 on 2019-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190803_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='target_group',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
