# Generated by Django 2.2.9 on 2020-01-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200102_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['date', 'title'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurs'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['nr'], 'verbose_name': 'Kurs-seksjon', 'verbose_name_plural': 'Kurs-seksjoner'},
        ),
        migrations.AlterField(
            model_name='course',
            name='bulk',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bolk'),
        ),
        migrations.AlterField(
            model_name='course',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentarer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Opprettet'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Slutt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_courses', to=settings.AUTH_USER_MODEL, verbose_name='Instruktør (follow)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_edited',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Sist redigert'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_courses', to=settings.AUTH_USER_MODEL, verbose_name='Sist redigert av'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_courses', to=settings.AUTH_USER_MODEL, verbose_name='Instruktør (lead)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Sted'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=140, null=True, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.Course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(null=True, verbose_name='Varighet'),
        ),
        migrations.AlterField(
            model_name='section',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='songs.Song', verbose_name='Sang'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=140, null=True, verbose_name='Tittel'),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='videos.Video', verbose_name='Video'),
        ),
    ]
