# Generated by Django 2.0.8 on 2019-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190803_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
