# Generated by Django 2.2.9 on 2020-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200104_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(default='7,5', null=True, verbose_name='Varighet'),
        ),
    ]
