# Generated by Django 2.2.9 on 2020-01-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200104_1835'),
        ('courses', '0012_auto_20200111_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='song2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_song2', to='songs.Song', verbose_name='Sang'),
        ),
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(default='7.5', null=True, verbose_name='Varighet'),
        ),
    ]
