# Generated by Django 2.0.8 on 2019-08-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190803_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='section',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video'),
        ),
    ]
