# Generated by Django 2.2.9 on 2020-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200111_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(default=7.5, null=True, verbose_name='Varighet'),
        ),
    ]
