# Generated by Django 2.2.9 on 2020-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200111_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration',
            field=models.FloatField(null=True, verbose_name='Varighet'),
        ),
    ]
