# Generated by Django 2.0.8 on 2019-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190804_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, to='courses.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
