# Generated by Django 2.0.8 on 2019-08-08 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190804_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='female_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='female_instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='male_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='male_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
