# Generated by Django 2.0.8 on 2019-08-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190809_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
