# Generated by Django 2.0.8 on 2019-08-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190809_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, default='default course', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='default section', max_length=140, null=True),
        ),
    ]
