# Generated by Django 2.0.8 on 2019-02-10 00:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
